# Generated by Django 4.1.3 on 2022-11-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mymessage',
        ),
    ]
